### ISSUE TITLE
Request was banned

### ISSUE THREAD

**Issue by 12345xinkai** [cotaku/Bibi-Release#103] opened 2024-05-07 09:44 UTC
![image](https://github.com/cotaku/Bibi-Release/assets/121651626/60278e79-2092-4225-8ec7-b4c138c9a4bf)
无法访问空间了
Cannot visit someone's channel

**Comment by cotaku** [comment] 2024-05-07 19:46
Duplicate of #104

**Comment by cotaku** [comment] 2024-05-08 00:14
fixed in v3.3.1.0

**Closed by cotaku** 2024-05-08 00:14 UTC
